# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: Rust
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.86.0

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests (default features)
        run: cargo test

      - name: Run tests (all features)
        run: cargo test --all-features
